name: haha-this-is-empty:D
top_k: 1
question_key: question
gt_key: answer
page_id_key: page_ids
truncate_len: null
max_page: 1000
max_character_per_page: 100000
use_mix: false
r_text_key: ${retrieval.r_text_key}
r_image_key: ${retrieval.r_image_key}
r_mix_key: ${retrieval.r_mix_key}
data_dir: ./data/${dataset.name}
result_dir: ./results/${dataset.name}/${run-name}
extract_path: ./tmp/${dataset.name}
document_path: ./data/${dataset.name}/documents
sample_path: ${dataset.data_dir}/samples.json
sample_with_retrieval_path: ${dataset.data_dir}/sample-with-retrieval-results.json